install webpack
when using nuxt-netlify-cms this error occured:
Error: Cannot find module 'extract-text-webpack-plugin'  

so, we need to install webpack or extract-text-webpack-plugin

https://stackoverflow.com/a/34012183